name: silex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  flutter_riverpod: ^3.3.1
  dio: ^5.9.2
  flutter_secure_storage: ^10.0.0
  socket_io_client: ^3.1.4
  cryptography: ^2.9.0
  crypto: ^3.0.6
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0D1210"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/user/
    - assets/icon/