// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTLATD3JKAVpHw3R0h9e-1zCtz4klaP68',
    appId: '1:664317060022:web:8a1b2e0a9b0e2fe7ea1717',
    messagingSenderId: '664317060022',
    projectId: 'silex-e598b',
    authDomain: 'silex-e598b.firebaseapp.com',
    storageBucket: 'silex-e598b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqiexmzgZDIg6EKT3XscI3Vo5I5s52MrU',
    appId: '1:664317060022:android:1358f549688ee664ea1717',
    messagingSenderId: '664317060022',
    projectId: 'silex-e598b',
    storageBucket: 'silex-e598b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ4eZ6TJZ3XfQ5NEYuKgp29Q9OFRUpaKs',
    appId: '1:664317060022:ios:b570a32b9cd155f4ea1717',
    messagingSenderId: '664317060022',
    projectId: 'silex-e598b',
    storageBucket: 'silex-e598b.firebasestorage.app',
    iosBundleId: 'com.example.silex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ4eZ6TJZ3XfQ5NEYuKgp29Q9OFRUpaKs',
    appId: '1:664317060022:ios:b570a32b9cd155f4ea1717',
    messagingSenderId: '664317060022',
    projectId: 'silex-e598b',
    storageBucket: 'silex-e598b.firebasestorage.app',
    iosBundleId: 'com.example.silex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTLATD3JKAVpHw3R0h9e-1zCtz4klaP68',
    appId: '1:664317060022:web:508969f219187fb6ea1717',
    messagingSenderId: '664317060022',
    projectId: 'silex-e598b',
    authDomain: 'silex-e598b.firebaseapp.com',
    storageBucket: 'silex-e598b.firebasestorage.app',
  );
}
